# Generated by Django 4.2.1 on 2023-05-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio42_api', '0002_remove_user_bio_alter_user_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('intra_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('kind', models.CharField(max_length=50)),
            ],
        ),
    ]
