# Generated by Django 4.2.1 on 2023-05-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio42_api', '0004_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('intra_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
