# Generated by Django 4.2.1 on 2023-05-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio42_api', '0006_cursusskill_cursususer_projectuser_projectusercursus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='intra_id',
            field=models.IntegerField(db_index=True, default=0, unique=True),
            preserve_default=False,
        ),
    ]
