# Generated by Django 4.2.1 on 2023-05-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio42_api', '0006_cursusskill_cursususer_projectuser_projectcursus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursususer',
            name='updated_at',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
