# Generated by Django 4.2.1 on 2023-05-30 22:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio42_api', '0006_cursusskill_cursususer_projectuser_projectcursus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursus',
            name='users',
        ),
        migrations.RemoveField(
            model_name='cursususer',
            name='skills',
        ),
        migrations.AddField(
            model_name='cursusskill',
            name='cursus_users',
            field=models.ManyToManyField(related_name='skills', through='portfolio42_api.CursusUserSkill', to='portfolio42_api.cursususer'),
        ),
        migrations.AddField(
            model_name='user',
            name='cursus',
            field=models.ManyToManyField(related_name='users', through='portfolio42_api.CursusUser', to='portfolio42_api.cursus'),
        ),
        migrations.AlterField(
            model_name='cursus',
            name='skills',
            field=models.ManyToManyField(related_name='cursus', through='portfolio42_api.CursusSkill', to='portfolio42_api.skill'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cursus',
            field=models.ManyToManyField(related_name='projects', through='portfolio42_api.ProjectCursus', to='portfolio42_api.cursus'),
        ),
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(related_name='projects', through='portfolio42_api.ProjectUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
