# Generated by Django 4.2.1 on 2023-06-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio42_api', '0007_remove_cursus_users_remove_cursususer_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursususer',
            name='updated_at',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
