# Generated by Django 4.2.7 on 2023-12-27 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio42_api', '0010_translationlanguage_projecttranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
    ]
